# Copyright 2025 Ross Golder
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).

from odoo import fields, models, api
from odoo.exceptions import ValidationError, AccessError
import base58
import hashlib
import hmac
import uuid
import logging
import secrets
import struct
from mnemonic import Mnemonic

_logger = logging.getLogger(__name__)

class CryptoBitcoinPrivateKey(models.Model):
    _name = 'crypto.bitcoin.private.key'
    _description = 'Crypto Bitcoin Private Key'
    _sql_constraints = [
        ('token_uuid_unique', 'unique(token_uuid)', 'Token UUID must be unique')
    ]

    name = fields.Char(string='Name', required=True)
    token_uuid = fields.Char(string='Token UUID', required=True, default=lambda self: str(uuid.uuid4()), 
                             copy=False, index=True)

    owner_id = fields.Many2one('res.partner', string='Owner')
    notes = fields.Text(string='Notes')
    
    # Key source tracking
    key_source = fields.Selection([
        ('mnemonic', 'From Mnemonic Phrase'),
        ('xprv', 'From Extended Private Key'),
        ('generated', 'Generated by Odoo')
    ], string='Key Source', required=True)
    
    # Linked public key
    public_key_id = fields.Many2one('crypto.bitcoin.public.key', string='Derived Public Key', readonly=True)
    
    # Related account public keys
    account_public_key_ids = fields.One2many('crypto.bitcoin.public.key', 'private_key_id', 
                                           string='Account Public Keys',
                                           domain=[('key_type', '=', 'account')])
    
    # Related multisig public keys
    multisig_public_key_ids = fields.One2many('crypto.bitcoin.public.key', 'private_key_id', 
                                            string='Multisig Public Keys',
                                            domain=[('key_type', '=', 'multisig')])
    
    # All related public keys
    all_public_key_ids = fields.One2many('crypto.bitcoin.public.key', 'private_key_id', 
                                        string='All Public Keys')

    # Fields retrieved from Vault (never stored in database)
    xprv = fields.Char(string='Extended Private Key', compute='_compute_vault_values', 
                       inverse='_inverse_vault_values', store=False, readonly=False)
    mnemonic = fields.Text(string='Mnemonic Phrase', compute='_compute_vault_values',
                          inverse='_inverse_vault_values', store=False, readonly=False)
    passphrase = fields.Char(string='BIP39 Passphrase', compute='_compute_vault_values',
                            inverse='_inverse_vault_values', store=False, readonly=False,
                            help="Optional 25th word for BIP39 mnemonic")

    # Computed fields for display
    derived_xpub = fields.Char(string='Derived XPUB', compute='_compute_derived_xpub', store=False)
    vault_status = fields.Char(string='Vault Status', compute='_compute_vault_values', store=False)
    
    # Derivation path XPUBs
    legacy_xpub = fields.Char(string='Legacy XPUB (m/44\'/0\'/0\')', compute='_compute_derivation_xpubs', store=False)
    nested_segwit_xpub = fields.Char(string='Nested SegWit XPUB (m/49\'/0\'/0\')', compute='_compute_derivation_xpubs', store=False)
    native_segwit_xpub = fields.Char(string='Native SegWit XPUB (m/84\'/0\'/0\')', compute='_compute_derivation_xpubs', store=False)
    taproot_xpub = fields.Char(string='Taproot XPUB (m/86\'/0\'/0\')', compute='_compute_derivation_xpubs', store=False)
    
    # Sample addresses for each type
    legacy_addresses = fields.Text(string='Legacy Addresses', compute='_compute_sample_addresses', store=False)
    nested_segwit_addresses = fields.Text(string='Nested SegWit Addresses', compute='_compute_sample_addresses', store=False)
    native_segwit_addresses = fields.Text(string='Native SegWit Addresses', compute='_compute_sample_addresses', store=False)
    taproot_addresses = fields.Text(string='Taproot Addresses', compute='_compute_sample_addresses', store=False)
    
    # Security settings
    max_derivation_count = fields.Integer(string='Max Derivation Count', default=50)

    def _inverse_vault_values(self):
        """Store private key data in vault"""
        for record in self:
            if record.token_uuid and (record.xprv or record.mnemonic):
                vault_data = {}
                
                if record.xprv:
                    vault_data['xprv'] = record.xprv
                if record.mnemonic:
                    vault_data['mnemonic'] = record.mnemonic
                if record.passphrase:
                    vault_data['passphrase'] = record.passphrase
                    
                if vault_data:
                    self.env['vault.connector'].set_secret(record.token_uuid, vault_data)

    @api.depends('token_uuid')
    def _compute_vault_values(self):
        """Retrieve private key data from vault using centralized service"""
        for record in self:
            if record.token_uuid:
                vault_result = record._get_private_key_from_vault(record.token_uuid)
                record.xprv = vault_result.get('xprv', '')
                record.mnemonic = vault_result.get('mnemonic', '')
                record.passphrase = vault_result.get('passphrase', '')
                record.vault_status = vault_result.get('status', '❌ Unknown error')
            else:
                record.xprv = ''
                record.mnemonic = ''
                record.passphrase = ''
                record.vault_status = '⚪ No token UUID'

    def _validate_mnemonic(self, words):
        """Validate BIP39 mnemonic phrase using proper library"""
        if not words:
            return False
            
        # Use official BIP39 validation
        mnemo = Mnemonic("english")
        return mnemo.check(words.strip())

    def _validate_xprv(self, xprv):
        """Validate extended private key format"""
        if not xprv or not xprv.startswith('xprv'):
            return False
            
        try:
            decoded = base58.b58decode_check(xprv)
            return len(decoded) == 78
        except Exception:
            return False

    def _derive_xpub_from_xprv(self, xprv):
        """Derive XPUB from XPRV using utility function"""
        return self.env['crypto.bip32.utils'].xprv_to_xpub(xprv)

    def _derive_xprv_from_mnemonic(self, mnemonic, passphrase=""):
        """Derive XPRV from mnemonic + passphrase using proper BIP39"""
        try:
            # Use proper BIP39 seed generation
            mnemo = Mnemonic("english")
            seed = mnemo.to_seed(mnemonic.strip(), passphrase)
            
            # Generate master private key using HMAC-SHA512
            hmac_result = hmac.new(b"Bitcoin seed", seed, hashlib.sha512).digest()
            master_private_key = hmac_result[:32]
            master_chain_code = hmac_result[32:]
            
            # Construct XPRV (mainnet version)
            version = b'\x04\x88\xAD\xE4'  # Mainnet xprv version
            depth = b'\x00'  # Master key depth
            parent_fingerprint = b'\x00\x00\x00\x00'  # Master key has no parent
            child_number = b'\x00\x00\x00\x00'  # Master key child number
            
            # Pad private key with 0x00 prefix for XPRV format
            padded_private_key = b'\x00' + master_private_key
            
            # Construct XPRV data
            xprv_data = version + depth + parent_fingerprint + child_number + master_chain_code + padded_private_key
            
            # Encode as base58check
            xprv = base58.b58encode_check(xprv_data).decode('ascii')
            return xprv
            
        except Exception as e:
            _logger.error(f"Failed to derive XPRV from mnemonic: {str(e)}")
            raise ValidationError(f"Failed to derive private key from mnemonic: {str(e)}")

    def _generate_mnemonic(self, word_count=24):
        """Generate a cryptographically secure BIP39 mnemonic"""
        # Calculate required entropy bits
        if word_count == 12:
            entropy_bits = 128
        elif word_count == 24:
            entropy_bits = 256
        else:
            raise ValidationError(f"Unsupported word count: {word_count}. Use 12 or 24.")
        
        # Use proper BIP39 mnemonic generation
        mnemo = Mnemonic("english")
        mnemonic = mnemo.generate(strength=entropy_bits)
        
        return mnemonic

    def _derive_custom_account_path(self, purpose, coin_type, account_index):
        """Derive custom account path: m/purpose'/coin_type'/account'"""
        self.ensure_one()
        
        try:
            # Parse master XPRV
            decoded = base58.b58decode_check(self.xprv)
            if len(decoded) != 78:
                raise ValidationError("Invalid master XPRV format")
                
            master_chain_code = decoded[13:45]
            master_private_key = decoded[45:78]
            
            # Derive m/purpose'
            purpose_key, purpose_chain = self.env['crypto.bip32.utils'].derive_child_key(
                master_private_key, master_chain_code, purpose, hardened=True, is_private=True
            )
            
            # Derive m/purpose'/coin_type'
            coin_key, coin_chain = self.env['crypto.bip32.utils'].derive_child_key(
                purpose_key, purpose_chain, coin_type, hardened=True, is_private=True
            )
            
            # Derive m/purpose'/coin_type'/account'
            account_key, account_chain = self.env['crypto.bip32.utils'].derive_child_key(
                coin_key, coin_chain, account_index, hardened=True, is_private=True
            )
            
            # Construct account-level XPRV
            version = b'\x04\x88\xAD\xE4'  # xprv mainnet version
            depth = b'\x03'  # Account level depth
            
            # Calculate parent fingerprint
            parent_pubkey_hash = hashlib.sha256(coin_key).digest()
            parent_fingerprint = hashlib.sha256(parent_pubkey_hash).digest()[:4]
            
            child_number = struct.pack('>I', account_index | 0x80000000)
            
            account_xprv_data = version + depth + parent_fingerprint + child_number + account_chain + account_key
            account_xprv = base58.b58encode_check(account_xprv_data).decode('ascii')
            
            # Derive corresponding XPUB
            account_xpub = self.env['crypto.bip32.utils'].xprv_to_xpub(account_xprv)
            
            return {
                'path': f"m/{purpose}'/{coin_type}'/{account_index}'",
                'xprv': account_xprv,
                'xpub': account_xpub,
            }
            
        except Exception as e:
            _logger.error(f"Failed to derive custom account path: {str(e)}")
            raise ValidationError(f"Custom account derivation failed: {str(e)}")

    def _generate_sample_addresses(self, xpub, base_path, address_type="bech32"):
        """Generate first 3 receive addresses from account XPUB"""
        self.ensure_one()
        
        try:
            addresses = []
            for i in range(3):
                addr_data = self.env['crypto.bip32.utils'].derive_address_from_xpub(
                    xpub, 0, i, base_path, address_type  # change=0 for receive addresses
                )
                addresses.append(f"{addr_data['path']}: {addr_data['address']}")
            
            return "\n".join(addresses)
            
        except Exception as e:
            _logger.warning(f"Failed to generate sample addresses: {str(e)}")
            return f"Error generating addresses: {str(e)}"

    @api.depends('xprv')
    def _compute_derived_xpub(self):
        """Compute XPUB from stored XPRV"""
        for record in self:
            if record.xprv:
                record.derived_xpub = record._derive_xpub_from_xprv(record.xprv)
            else:
                record.derived_xpub = ""

    @api.depends('xprv')
    def _compute_derivation_xpubs(self):
        """Compute XPUBs for different derivation paths"""
        for record in self:
            if record.xprv:
                try:
                    # Legacy BIP44: m/44'/0'/0'
                    legacy_data = self.env['crypto.bip32.utils'].derive_bip44_account(record.xprv, 0, 0)
                    record.legacy_xpub = legacy_data['xpub']
                    
                    # Nested SegWit BIP49: m/49'/0'/0' (simulated using BIP44 with purpose 49)
                    nested_data = record._derive_custom_account_path(49, 0, 0)
                    record.nested_segwit_xpub = nested_data['xpub']
                    
                    # Native SegWit BIP84: m/84'/0'/0' (simulated using BIP44 with purpose 84)
                    native_data = record._derive_custom_account_path(84, 0, 0)
                    record.native_segwit_xpub = native_data['xpub']
                    
                    # Taproot BIP86: m/86'/0'/0' (simulated using BIP44 with purpose 86)
                    taproot_data = record._derive_custom_account_path(86, 0, 0)
                    record.taproot_xpub = taproot_data['xpub']
                    
                except Exception as e:
                    _logger.warning(f"Failed to compute derivation XPUBs for {record.name}: {str(e)}")
                    record.legacy_xpub = ""
                    record.nested_segwit_xpub = ""
                    record.native_segwit_xpub = ""
                    record.taproot_xpub = ""
            else:
                record.legacy_xpub = ""
                record.nested_segwit_xpub = ""
                record.native_segwit_xpub = ""
                record.taproot_xpub = ""

    @api.depends('legacy_xpub', 'nested_segwit_xpub', 'native_segwit_xpub', 'taproot_xpub')
    def _compute_sample_addresses(self):
        """Compute sample addresses for each derivation path"""
        for record in self:
            try:
                # Generate first 3 addresses for each type with correct address formats
                if record.legacy_xpub:
                    record.legacy_addresses = record._generate_sample_addresses(record.legacy_xpub, "m/44'/0'/0'", "p2pkh")
                else:
                    record.legacy_addresses = ""
                    
                if record.nested_segwit_xpub:
                    record.nested_segwit_addresses = record._generate_sample_addresses(record.nested_segwit_xpub, "m/49'/0'/0'", "p2sh")
                else:
                    record.nested_segwit_addresses = ""
                    
                if record.native_segwit_xpub:
                    record.native_segwit_addresses = record._generate_sample_addresses(record.native_segwit_xpub, "m/84'/0'/0'", "bech32")
                else:
                    record.native_segwit_addresses = ""
                    
                if record.taproot_xpub:
                    record.taproot_addresses = record._generate_sample_addresses(record.taproot_xpub, "m/86'/0'/0'", "taproot")
                else:
                    record.taproot_addresses = ""
                    
            except Exception as e:
                _logger.warning(f"Failed to compute sample addresses for {record.name}: {str(e)}")
                record.legacy_addresses = ""
                record.nested_segwit_addresses = ""
                record.native_segwit_addresses = ""
                record.taproot_addresses = ""

    def _get_private_key_from_vault(self, token_uuid):
        """
        Centralized method to get private key data from vault
        Returns: {'xprv': str, 'mnemonic': str, 'passphrase': str, 'status': str}
        """
        try:
            vault_connector = self.env['vault.connector']
            vault_data = vault_connector.get_secret(token_uuid)
            
            if vault_data:
                has_xprv = bool(vault_data.get('xprv'))
                has_mnemonic = bool(vault_data.get('mnemonic'))
                
                if has_xprv or has_mnemonic:
                    key_type = 'XPRV' if has_xprv else 'Mnemonic'
                    if has_xprv and has_mnemonic:
                        key_type = 'XPRV & Mnemonic'
                    
                    return {
                        'xprv': vault_data.get('xprv', ''),
                        'mnemonic': vault_data.get('mnemonic', ''),
                        'passphrase': vault_data.get('passphrase', ''),
                        'status': f'✅ Connected - {key_type} available'
                    }
                else:
                    return {
                        'xprv': '',
                        'mnemonic': '',
                        'passphrase': '',
                        'status': '⚠️ No private key data in vault'
                    }
            else:
                return {
                    'xprv': '',
                    'mnemonic': '',
                    'passphrase': '',
                    'status': '⚠️ Secret not found in vault'
                }
                
        except Exception as e:
            error_msg = str(e)
            _logger.warning(f"Vault error for private key token {token_uuid}: {error_msg}")
            
            # Categorize errors for user-friendly display
            if 'sealed' in error_msg.lower():
                status = '🔒 Vault is sealed - unseal required'
            elif 'not accessible' in error_msg or 'environment variables' in error_msg:
                status = '❌ Vault not configured'
            elif 'not found' in error_msg:
                status = '⚠️ Secret not found in vault'
            elif 'access denied' in error_msg or 'token' in error_msg:
                status = '❌ Vault access denied'
            else:
                status = f'❌ Vault error: {error_msg}'
                
            return {
                'xprv': '',
                'mnemonic': '',
                'passphrase': '',
                'status': status
            }


    @api.model
    def create(self, vals):
        """Enhanced create method with validation and key processing"""
        # Validate inputs based on key source
        if vals.get('key_source') == 'mnemonic':
            if not vals.get('mnemonic'):
                raise ValidationError("Mnemonic phrase is required")
            if not self._validate_mnemonic(vals['mnemonic']):
                raise ValidationError("Invalid mnemonic phrase format")
                
        elif vals.get('key_source') == 'xprv':
            if not vals.get('xprv'):
                raise ValidationError("Extended private key is required")
            if not self._validate_xprv(vals['xprv']):
                raise ValidationError("Invalid extended private key format")
                
        # Create the record
        record = super(CryptoBitcoinPrivateKey, self).create(vals)
        
        # Process the key data after creation
        record._process_key_creation()
        
        return record

    def _process_key_creation(self):
        """Process key creation based on source type"""
        self.ensure_one()
        
        if self.key_source == 'mnemonic' and self.mnemonic:
            # Derive XPRV from mnemonic
            xprv = self._derive_xprv_from_mnemonic(self.mnemonic, self.passphrase or "")
            
            # Update vault with complete data
            vault_data = {
                'mnemonic': self.mnemonic,
                'passphrase': self.passphrase or "",
                'xprv': xprv
            }
            self.env['vault.connector'].set_secret(self.token_uuid, vault_data)
            
        elif self.key_source == 'xprv' and self.xprv:
            # Store XPRV only
            vault_data = {'xprv': self.xprv}
            self.env['vault.connector'].set_secret(self.token_uuid, vault_data)
            
        elif self.key_source == 'generated':
            # Generate new mnemonic and derive XPRV
            mnemonic = self._generate_mnemonic(24)
            xprv = self._derive_xprv_from_mnemonic(mnemonic, "")
            
            # Store complete generated data
            vault_data = {
                'mnemonic': mnemonic,
                'passphrase': "",
                'xprv': xprv
            }
            self.env['vault.connector'].set_secret(self.token_uuid, vault_data)

    def action_create_public_key(self):
        """Create a linked public key from this private key"""
        self.ensure_one()
        
        if self.public_key_id:
            raise ValidationError("Public key already created for this private key")
            
        if not self.derived_xpub:
            raise ValidationError("Cannot create public key: XPUB derivation failed")
            
        # Create the public key record
        public_key = self.env['crypto.bitcoin.public.key'].create({
            'name': f"{self.name} (Master)",
            'owner_id': self.owner_id.id if self.owner_id else False,
            'private_key_id': self.id,  # Link back to this private key
            'notes': f"Master public key derived from private key: {self.name}",
            'max_derivation_count': self.max_derivation_count,
            'key_type': 'master',
            'derivation_path': 'm/',
        })
        
        # Store the XPUB in vault for the public key
        public_key_vault_data = {'xpub': self.derived_xpub}
        self.env['vault.connector'].set_secret(public_key.token_uuid, public_key_vault_data)
        
        # Link the keys
        self.public_key_id = public_key.id
        
        return {
            'type': 'ir.actions.act_window',
            'name': 'Created Public Key',
            'res_model': 'crypto.bitcoin.public.key',
            'res_id': public_key.id,
            'view_mode': 'form',
            'target': 'current',
        }

    def action_refresh_vault_status(self):
        """Manually refresh vault status and key data"""
        self.ensure_one()
        self._compute_vault_status()
        self._compute_vault_values()
        self._compute_derived_xpub()
        
        return {
            'type': 'ir.actions.client',
            'tag': 'reload',
        }

    def create_account_public_key(self, account_index, partner_id=None, name_suffix=None):
        """
        Create account-level public key for BIP44 account
        
        Args:
            account_index (int): BIP44 account index (0-2147483647)
            partner_id (int, optional): Partner to assign this account to
            name_suffix (str, optional): Custom name suffix
            
        Returns:
            crypto.bitcoin.public.key: Created account public key record
        """
        self.ensure_one()
        
        if account_index < 0 or account_index > 2147483647:  # 2^31 - 1
            raise ValidationError("Account index must be between 0 and 2147483647")
            
        # Check if account already exists
        existing_account = self.env['crypto.bitcoin.public.key'].search([
            ('private_key_id', '=', self.id),
            ('key_type', '=', 'account'),
            ('account_index', '=', account_index)
        ])
        if existing_account:
            raise ValidationError(f"Account {account_index} public key already exists")
            
        # Derive account-level keys using utility
        account_data = self.env['crypto.bip32.utils'].derive_bip44_account(self.xprv, account_index)
        
        # Determine name
        if name_suffix:
            name = f"{self.name} - Account {account_index} ({name_suffix})"
        else:
            name = f"{self.name} - Account {account_index}"
            
        # Get partner if provided
        partner = None
        if partner_id:
            partner = self.env['res.partner'].browse(partner_id)
            if not partner.exists():
                raise ValidationError("Invalid partner ID")
            name += f" - {partner.name}"
        
        # Create account public key record
        account_public_key = self.env['crypto.bitcoin.public.key'].create({
            'name': name,
            'owner_id': self.owner_id.id if self.owner_id else False,
            'partner_id': partner_id,
            'private_key_id': self.id,
            'key_type': 'account',
            'account_index': account_index,
            'derivation_path': account_data['path'],
            'fingerprint': account_data['fingerprint'],
            'notes': f"Account-level public key for BIP44 account {account_index}" + 
                    (f" assigned to {partner.name}" if partner else ""),
            'max_derivation_count': self.max_derivation_count,
        })
        
        # Store XPUB in vault
        vault_data = {'xpub': account_data['xpub']}
        self.env['vault.connector'].set_secret(account_public_key.token_uuid, vault_data)
        
        _logger.info(f"Created account {account_index} public key" + 
                    (f" for {partner.name}" if partner else ""))
        return account_public_key

    def create_multisig_public_key(self, account_index, script_type, cosigner_index=0, 
                                 multisig_wallet_id=None, name_suffix=None):
        """
        Create multisig-level public key for BIP48 multisig
        
        Args:
            account_index (int): BIP48 account index (0-2147483647)
            script_type (str): 'p2sh', 'p2wsh', or 'p2sh_p2wsh'
            cosigner_index (int): Cosigner index for this key
            multisig_wallet_id (int, optional): Associated multisig wallet
            name_suffix (str, optional): Custom name suffix
            
        Returns:
            crypto.bitcoin.public.key: Created multisig public key record
        """
        self.ensure_one()
        
        if account_index < 0 or account_index > 2147483647:  # 2^31 - 1
            raise ValidationError("Account index must be between 0 and 2147483647")
            
        # Check if this multisig setup already exists
        existing_multisig = self.env['crypto.bitcoin.public.key'].search([
            ('private_key_id', '=', self.id),
            ('key_type', '=', 'multisig'),
            ('account_index', '=', account_index),
            ('script_type', '=', script_type),
            ('cosigner_index', '=', cosigner_index)
        ])
        if existing_multisig:
            raise ValidationError(f"Multisig key for account {account_index}, script type {script_type}, cosigner {cosigner_index} already exists")
            
        # Derive multisig-level keys using utility
        multisig_data = self.env['crypto.bip32.utils'].derive_bip48_multisig(
            self.xprv, account_index, script_type, cosigner_index
        )
        
        # Determine name
        script_name = dict(self.env['crypto.bitcoin.public.key']._fields['script_type'].selection).get(script_type, script_type.upper())
        if name_suffix:
            name = f"{self.name} - Multisig Account {account_index} {script_name} Cosigner {cosigner_index} ({name_suffix})"
        else:
            name = f"{self.name} - Multisig Account {account_index} {script_name} Cosigner {cosigner_index}"
            
        # Get multisig wallet if provided
        multisig_wallet = None
        if multisig_wallet_id:
            multisig_wallet = self.env['crypto.bitcoin.multisig.wallet'].browse(multisig_wallet_id)
            if not multisig_wallet.exists():
                raise ValidationError("Invalid multisig wallet ID")
            name += f" - {multisig_wallet.name}"
        
        # Create multisig public key record
        multisig_public_key = self.env['crypto.bitcoin.public.key'].create({
            'name': name,
            'owner_id': self.owner_id.id if self.owner_id else False,
            'private_key_id': self.id,
            'key_type': 'multisig',
            'account_index': account_index,
            'script_type': script_type,
            'cosigner_index': cosigner_index,
            'multisig_wallet_id': multisig_wallet_id,
            'derivation_path': multisig_data['path'],
            'fingerprint': multisig_data['fingerprint'],
            'notes': f"BIP48 multisig public key for account {account_index}, {script_name}, cosigner {cosigner_index}" + 
                    (f" associated with {multisig_wallet.name}" if multisig_wallet else ""),
            'max_derivation_count': self.max_derivation_count,
        })
        
        # Store XPUB in vault
        vault_data = {'xpub': multisig_data['xpub']}
        self.env['vault.connector'].set_secret(multisig_public_key.token_uuid, vault_data)
        
        _logger.info(f"Created multisig account {account_index} {script_type} cosigner {cosigner_index} public key" + 
                    (f" for {multisig_wallet.name}" if multisig_wallet else ""))
        return multisig_public_key

    def action_create_account_public_key_wizard(self):
        """Launch wizard to create account public key"""
        self.ensure_one()
        
        if not self.xprv:
            raise ValidationError("XPRV required to derive account public keys")
            
        return {
            'type': 'ir.actions.act_window',
            'name': 'Create Account Public Key',
            'res_model': 'wizard.create.account.public.key',
            'view_mode': 'form',
            'target': 'new',
            'context': {
                'default_private_key_id': self.id,
            }
        }

    def action_create_multisig_public_key_wizard(self):
        """Launch wizard to create multisig public key"""
        self.ensure_one()
        
        if not self.xprv:
            raise ValidationError("XPRV required to derive multisig public keys")
            
        return {
            'type': 'ir.actions.act_window',
            'name': 'Create Multisig Public Key',
            'res_model': 'wizard.create.multisig.public.key',
            'view_mode': 'form',
            'target': 'new',
            'context': {
                'default_private_key_id': self.id,
            }
        }

    def action_view_public_key(self):
        """View the linked public key"""
        self.ensure_one()
        
        if not self.public_key_id:
            raise ValidationError("No public key linked to this private key")
            
        return {
            'type': 'ir.actions.act_window',
            'name': 'Linked Public Key',
            'res_model': 'crypto.bitcoin.public.key',
            'res_id': self.public_key_id.id,
            'view_mode': 'form',
            'target': 'current',
        }

