from . import crypto_bitcoin_address
from . import crypto_bitcoin_transaction
from . import crypto_bitcoin_wallet
from . import crypto_lightning_address
from . import crypto_lightning_payment_form
from . import crypto_lightning_payment_processor
from . import crypto_lightning_service_provider
from . import res_currency_cryptocurrency
from . import res_partner